/**
 * Presentation component.
 *
 * Displays alerts generated by the backend Alert Service.
 *
 * No business logic belongs here.
 *
 * ===============================================================
 */

const AgencyAlerts = ({ alerts = [] }) => {

  const alertStyles = (type) => {

    switch (type) {

      case "danger":
        return "border-red-500/30 bg-red-500/10";

      case "warning":
        return "border-yellow-500/30 bg-yellow-500/10";

      case "success":
        return "border-emerald-500/30 bg-emerald-500/10";

      default:
        return "border-cyan-500/30 bg-cyan-500/10";

    }

  };

  return (

    <section className="rounded-3xl border border-slate-800 bg-slate-900 shadow-xl">

      <div className="border-b border-slate-800 p-6">

        <h2 className="text-xl font-bold text-white">

          Agency Alerts

        </h2>

        <p className="mt-1 text-sm text-slate-400">

          Live operational alerts generated automatically.

        </p>

      </div>

      <div className="space-y-4 p-6">

        {alerts.length === 0 ? (

          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-5">

            <p className="text-emerald-300">

              ✅ No operational alerts.

            </p>

          </div>

        ) : (

          alerts.map((alert) => (

            <div
              key={alert.id}
              className={`
                flex
                items-start
                gap-4
                rounded-2xl
                border
                p-4
                ${alertStyles(alert.type)}
              `}
            >

              <div className="text-2xl">

                {alert.icon}

              </div>

              <div className="flex-1">

                <h3 className="font-semibold text-white">

                  {alert.title}

                </h3>

                <p className="mt-1 text-sm text-slate-300">

                  {alert.message}

                </p>

              </div>

            </div>

          ))

        )}

      </div>

    </section>

  );

};

export default AgencyAlerts;