/**
 * ==========================================================
 *
 * AI ANALYTICS
 *
 * Purpose
 * ----------------------------------------------------------
 * Displays AI performance metrics generated by LeadFlow AI.
 *
 * This widget helps administrators understand how the
 * AI qualification engine is performing across all leads.
 *
 * It answers questions such as:
 *
 * • How many Hot leads were detected?
 * • Average qualification score?
 * • Average budget confidence?
 * • Average location confidence?
 * • Average bedroom confidence?
 * • Average move-date confidence?
 * • AI qualification rate?
 *
 * FEATURES
 * --------
 * ✓ AI Health Summary
 * ✓ Qualification metrics
 * ✓ Confidence metrics
 * ✓ Intent distribution
 * ✓ Beautiful KPI cards
 * ✓ Responsive layout
 * ✓ Empty state
 *
 * USED BY
 * -------
 * AdminDashboard.jsx
 *
 * EXPECTED DATA
 * -------------
 *
 * {
 *   totalLeads:120,
 *   qualifiedLeads:68,
 *   hotLeads:25,
 *   averageScore:72,
 *
 *   averageBuyingIntent:75,
 *
 *   intentDistribution: {
 *     rent: 40,
 *     buy: 35,
 *     property_search: 25
 *   },
 *
 *   averageBudgetConfidence:81,
 *   averageLocationConfidence:90,
 *   averageBedroomConfidence:76,
 *   averageMoveDateConfidence:64
 * }
 *
 * ==========================================================
 */

const AIAnalytics = ({ aiAnalytics = {} }) => {
  const {
    averageScore = 0,
    averageBuyingIntent = 0,
    urgentLeads = 0,
    averageBudgetConfidence = 0,
    averageLocationConfidence = 0,

    /**
     * ======================================================
     * INTENT DISTRIBUTION
     * ======================================================
     *
     * Backend source of truth:
     *
     * analytics.intentDistribution
     *
     * Canonical intent values:
     *
     * rent
     * buy
     * property_search
     *
     * IMPORTANT:
     *
     * Do NOT use:
     *
     *     aiAnalytics.intent
     *
     * and do NOT use averageBuyingIntent as the categorical
     * lead intent.
     */
    intentDistribution = {},
  } = aiAnalytics;

  /**
   * ======================================================
   * NORMALIZED INTENT COUNTS
   * ======================================================
   *
   * Always provide safe numeric defaults so the UI does not
   * break when one of the intent categories is missing.
   */

  const rentIntent =
    Number(
      intentDistribution?.rent
    ) || 0;

  const buyIntent =
    Number(
      intentDistribution?.buy
    ) || 0;

  const propertySearchIntent =
    Number(
      intentDistribution?.property_search
    ) || 0;

  /**
   * ======================================================
   * EMPTY STATE
   * ======================================================
   */

  if (
    !averageScore &&
    !averageBuyingIntent &&
    !urgentLeads &&
    !rentIntent &&
    !buyIntent &&
    !propertySearchIntent
  ) {
    return (
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-8">

        <h2 className="text-2xl font-bold text-white">
          🤖 AI Analytics
        </h2>

        <div className="mt-8 text-center">

          <p className="text-slate-400">
            AI analytics are not available yet.
          </p>

        </div>

      </section>
    );
  }

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6">

      {/* HEADER */}

      <div className="mb-8">

        <h2 className="text-2xl font-bold text-white">
          🤖 AI Analytics
        </h2>

        <p className="mt-2 text-slate-400">
          Performance of the LeadFlow AI qualification engine.
        </p>

      </div>

      {/* SUMMARY */}

      <div className="grid gap-6 md:grid-cols-4">

        <div className="rounded-xl bg-slate-950 p-5">

          <p className="text-sm text-slate-400">
            Average AI Score
          </p>

          <h3 className="mt-3 text-4xl font-bold text-cyan-400">
            {averageScore}
          </h3>

        </div>

        <div className="rounded-xl bg-slate-950 p-5">

          <p className="text-sm text-slate-400">
            Buying Intent
          </p>

          <h3 className="mt-3 text-4xl font-bold text-green-400">
            {averageBuyingIntent}%
          </h3>

        </div>

        <div className="rounded-xl bg-slate-950 p-5">

          <p className="text-sm text-slate-400">
            Urgent Leads
          </p>

          <h3 className="mt-3 text-4xl font-bold text-orange-400">
            {urgentLeads}
          </h3>

        </div>

        <div className="rounded-xl bg-slate-950 p-5">

          <p className="text-sm text-slate-400">
            AI Health
          </p>

          <h3 className="mt-3 text-4xl font-bold text-purple-400">
            Excellent
          </h3>

        </div>

      </div>

      {/* ======================================================
          INTENT DISTRIBUTION
      ====================================================== */}

      <div className="mt-10">

        <h3 className="mb-5 text-xl font-semibold text-white">
          Lead Intent Distribution
        </h3>

        <div className="grid gap-4 md:grid-cols-3">

          {/* RENT */}

          <div className="rounded-xl bg-slate-950 p-5">

            <p className="text-sm text-slate-400">
              Rent
            </p>

            <h3 className="mt-3 text-3xl font-bold text-blue-400">
              {rentIntent}
            </h3>

            <p className="mt-2 text-xs text-slate-500">
              Customers explicitly looking to rent or lease.
            </p>

          </div>

          {/* BUY */}

          <div className="rounded-xl bg-slate-950 p-5">

            <p className="text-sm text-slate-400">
              Buy
            </p>

            <h3 className="mt-3 text-3xl font-bold text-green-400">
              {buyIntent}
            </h3>

            <p className="mt-2 text-xs text-slate-500">
              Customers explicitly looking to buy or purchase.
            </p>

          </div>

          {/* PROPERTY SEARCH */}

          <div className="rounded-xl bg-slate-950 p-5">

            <p className="text-sm text-slate-400">
              Property Search
            </p>

            <h3 className="mt-3 text-3xl font-bold text-cyan-400">
              {propertySearchIntent}
            </h3>

            <p className="mt-2 text-xs text-slate-500">
              Customers searching for property without specifying
              rent or buy.
            </p>

          </div>

        </div>

      </div>

      {/* CONFIDENCE SCORES */}

      <div className="mt-10">

        <h3 className="mb-5 text-xl font-semibold text-white">
          Confidence Scores
        </h3>

        <div className="space-y-5">

          <ConfidenceBar
            label="Budget Confidence"
            value={averageBudgetConfidence}
            color="bg-cyan-500"
          />

          <ConfidenceBar
            label="Location Confidence"
            value={averageLocationConfidence}
            color="bg-green-500"
          />

        </div>

      </div>

    </section>
  );
};

/**
 * ==========================================================
 * INTERNAL COMPONENT
 * ==========================================================
 */

const ConfidenceBar = ({
  label,
  value,
  color,
}) => {
  return (
    <div>

      <div className="mb-2 flex items-center justify-between">

        <span className="text-slate-300">
          {label}
        </span>

        <span className="font-semibold text-white">
          {value}%
        </span>

      </div>

      <div className="h-3 overflow-hidden rounded-full bg-slate-800">

        <div
          className={`${color} h-full rounded-full transition-all duration-500`}
          style={{
            width: `${value}%`,
          }}
        />

      </div>

    </div>
  );
};

export default AIAnalytics;