/**
 * ==========================================================
 * AI-powered property recommendations for an agent's
 * assigned leads.
 *
 * Instead of browsing all listings, the agent receives
 * the best property matches generated by LeadFlow AI.
 *
 * USED BY
 * ----------------------------------------------------------
 * AgentDashboard.jsx
 *
 * Future Backend
 * ----------------------------------------------------------
 * GET /api/agent/recommended-properties
 *
 * Future AI Service
 * ----------------------------------------------------------
 * recommendationEngine.matchLeadToProperty()
 *
 * ==========================================================
 */

import { useEffect, useState } from "react";

import { useNavigate } from "react-router-dom";

import {
  MapPin,
  BedDouble,
  Home,
  BadgeDollarSign,
  Sparkles,
  ArrowRight,
  Share2,
  UserRound,
} from "lucide-react";

const RecommendedProperties = () => {

  const navigate = useNavigate();

  //----------------------------------------------------------
  // STATE
  //----------------------------------------------------------

  const [recommendations, setRecommendations] = useState([]);

  //----------------------------------------------------------
  // TEMPORARY MOCK DATA
  //----------------------------------------------------------

  useEffect(() => {

    setRecommendations([

      {
        id: 1,

        leadId: "L001",

        leadName: "James Mwangi",

        propertyId: "P101",

        propertyName: "Westlands Executive Apartment",

        location: "Westlands",

        type: "Apartment",

        bedrooms: 3,

        price: "KES 12,500,000",

        matchScore: 96,

        image:
          "https://placehold.co/600x400?text=Apartment",

        reasons: [

          "Matches customer budget",

          "Preferred Westlands location",

          "Requested 3 bedrooms",

          "Close to CBD",

        ],

      },

      {
        id: 2,

        leadId: "L002",

        leadName: "Sarah Achieng",

        propertyId: "P205",

        propertyName: "Karen Family Maisonette",

        location: "Karen",

        type: "Maisonette",

        bedrooms: 4,

        price: "KES 34,000,000",

        matchScore: 92,

        image:
          "https://placehold.co/600x400?text=Maisonette",

        reasons: [

          "Family-sized home",

          "Secure neighborhood",

          "Private garden",

          "Budget compatible",

        ],

      },

    ]);

  }, []);

  //----------------------------------------------------------
  // MATCH SCORE COLORS
  //----------------------------------------------------------

  const scoreColor = (score) => {

    if (score >= 90)
      return "text-emerald-400";

    if (score >= 75)
      return "text-cyan-400";

    return "text-orange-400";

  };

  //----------------------------------------------------------
  // LOADING / EMPTY STATE
  //----------------------------------------------------------

  if (!recommendations.length) {

    return (

      <section
        className="
          rounded-3xl
          border
          border-slate-800
          bg-slate-900
          p-6
          shadow-xl
        "
      >

        <p className="text-sm text-slate-400">
          Loading AI property recommendations...
        </p>

      </section>

    );

  }

  //----------------------------------------------------------
  // UI
  //----------------------------------------------------------

  return (

    <section
      className="
        rounded-3xl
        border
        border-slate-800
        bg-slate-900
        shadow-xl
      "
    >

      {/*==============================================
          HEADER
      ==============================================*/}

      <div
        className="
          border-b
          border-slate-800
          p-6
        "
      >

        <div
          className="
            flex
            flex-col
            gap-4
            lg:flex-row
            lg:items-center
            lg:justify-between
          "
        >

          <div>

            <h2
              className="
                flex
                items-center
                gap-2
                text-2xl
                font-bold
                text-white
              "
            >

              <Sparkles className="text-cyan-400" />

              AI Recommended Properties

            </h2>

            <p
              className="
                mt-2
                text-sm
                text-slate-400
              "
            >
              Smart property matches generated for your active
              customer leads.
            </p>

          </div>

          <div
            className="
              rounded-full
              border
              border-cyan-500/20
              bg-cyan-500/10
              px-5
              py-2
            "
          >

            <p className="text-xs text-cyan-300">

              Recommendations

            </p>

            <p className="text-lg font-bold text-white">

              {recommendations.length}

            </p>

          </div>

        </div>

      </div>

      {/*==============================================
          RECOMMENDATIONS
      ==============================================*/}

      <div
        className="
          grid
          gap-6
          p-6
          xl:grid-cols-2
        "
      >

        {recommendations.map((property) => (

          <article
            key={property.id}
            className="
              overflow-hidden
              rounded-2xl
              border
              border-slate-800
              bg-slate-950
              transition-all
              duration-300
              hover:border-cyan-500/40
              hover:shadow-lg
              hover:shadow-cyan-900/20
            "
          >

            {/* Property Image */}

            <img
              src={property.image}
              alt={property.propertyName}
              className="
                h-56
                w-full
                object-cover
              "
            />

            <div className="p-6">

              {/* Lead */}

              <div
                className="
                  mb-5
                  flex
                  items-center
                  justify-between
                "
              >

                <div
                  className="
                    flex
                    items-center
                    gap-2
                  "
                >

                  <UserRound
                    size={18}
                    className="text-cyan-400"
                  />

                  <span
                    className="
                      text-sm
                      font-medium
                      text-slate-300
                    "
                  >

                    {property.leadName}

                  </span>

                </div>

                <span
                  className={`
                    rounded-full
                    bg-emerald-500/10
                    px-3
                    py-1
                    text-sm
                    font-bold
                    ${scoreColor(property.matchScore)}
                  `}
                >

                  {property.matchScore}% Match

                </span>

              </div>

              {/* Property Name */}

              <h3
                className="
                  text-xl
                  font-bold
                  text-white
                "
              >

                {property.propertyName}

              </h3>

              {/* Property Details */}

              <div
                className="
                  mt-5
                  grid
                  grid-cols-2
                  gap-4
                "
              >

                <div className="flex items-center gap-2">

                  <MapPin
                    size={18}
                    className="text-cyan-400"
                  />

                  <span className="text-sm text-slate-300">

                    {property.location}

                  </span>

                </div>

                <div className="flex items-center gap-2">

                  <Home
                    size={18}
                    className="text-cyan-400"
                  />

                  <span className="text-sm text-slate-300">

                    {property.type}

                  </span>

                </div>

                <div className="flex items-center gap-2">

                  <BedDouble
                    size={18}
                    className="text-cyan-400"
                  />

                  <span className="text-sm text-slate-300">

                    {property.bedrooms} Bedrooms

                  </span>

                </div>

                <div className="flex items-center gap-2">

                  <BadgeDollarSign
                    size={18}
                    className="text-cyan-400"
                  />

                  <span className="text-sm text-slate-300">

                    {property.price}

                  </span>

                </div>

              </div>

              {/*==============================================
                  AI MATCH REASONS
              ==============================================*/}

              <div className="mt-6">

                <h4
                  className="
                    mb-3
                    text-sm
                    font-semibold
                    uppercase
                    tracking-wide
                    text-cyan-300
                  "
                >
                  Why LeadFlow AI recommends this property
                </h4>

                <ul className="space-y-2">

                  {property.reasons.map((reason) => (

                    <li
                      key={reason}
                      className="
                        flex
                        items-center
                        gap-2
                        text-sm
                        text-slate-300
                      "
                    >

                      <span className="text-emerald-400">
                        ✓
                      </span>

                      {reason}

                    </li>

                  ))}

                </ul>

              </div>

              {/*==============================================
                  ACTIONS
              ==============================================*/}

              <div
                className="
                  mt-8
                  flex
                  flex-wrap
                  gap-3
                "
              >

                {/* View Property */}

                <button
                  onClick={() =>
                    navigate(
                      `/agent/properties/${property.propertyId}`
                    )
                  }
                  className="
                    flex
                    items-center
                    gap-2
                    rounded-xl
                    bg-cyan-500
                    px-5
                    py-3
                    text-sm
                    font-semibold
                    text-slate-950
                    transition
                    hover:bg-cyan-400
                  "
                >

                  View Property

                  <ArrowRight size={18} />

                </button>

                {/* Share Listing */}

                <button
                  onClick={() =>
                    navigate(
                      `/agent/properties/${property.propertyId}/share`
                    )
                  }
                  className="
                    flex
                    items-center
                    gap-2
                    rounded-xl
                    border
                    border-slate-700
                    bg-slate-900
                    px-5
                    py-3
                    text-sm
                    font-semibold
                    text-white
                    transition
                    hover:border-cyan-500/40
                    hover:bg-slate-800
                  "
                >

                  <Share2 size={18} />

                  Share Listing

                </button>

                {/* Open Lead */}

                <button
                  onClick={() =>
                    navigate(
                      `/agent/leads/${property.leadId}`
                    )
                  }
                  className="
                    rounded-xl
                    border
                    border-slate-700
                    bg-slate-900
                    px-5
                    py-3
                    text-sm
                    font-semibold
                    text-white
                    transition
                    hover:border-cyan-500/40
                    hover:bg-slate-800
                  "
                >

                  Open Lead

                </button>

              </div>

            </div>

          </article>

        ))}

      </div>

      {/*==============================================
          FOOTER
      ==============================================*/}

      <div
        className="
          flex
          flex-col
          gap-4
          border-t
          border-slate-800
          p-6
          lg:flex-row
          lg:items-center
          lg:justify-between
        "
      >

        <p
          className="
            text-sm
            text-slate-400
          "
        >
          LeadFlow AI continuously analyzes customer preferences,
          budgets and locations to recommend the properties most
          likely to convert into successful sales.
        </p>

        <button
          onClick={() =>
            navigate("/agent/properties")
          }
          className="
            inline-flex
            items-center
            gap-2
            rounded-xl
            bg-violet-500
            px-6
            py-3
            text-sm
            font-semibold
            text-white
            transition
            hover:bg-violet-400
          "
        >

          Browse All Properties

          <ArrowRight size={18} />

        </button>

      </div>

    </section>

  );

};

export default RecommendedProperties;